---
ID: "98d4155a-577d-4e41-ae83-085b834d0681"
Parent: "b16b8359-d784-4f37-86c5-1469b2c59892"
Template: "b16b8359-d784-4f37-86c5-1469b2c59892"
Path: "/sitecore/templates/Feature/Components Library/Navigation-CL/Rendering Parameters/Link/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "18d80bd5-270f-489e-a5a3-5ad9f283e9ca"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240520T120933Z
