---
ID: "28fa02c3-1b6c-48e4-a1a2-791f429b57e6"
Parent: "534031d5-864b-4d39-91b3-43a4912c4fe4"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/HeadlessTenant/Hublot/Presentation/Headless Variants/Event List/Default
BranchID: "cd388a73-d20c-42bd-b9d2-bd5caec24a19"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{5A26A76C-2881-46EA-9291-72350D2105DE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240613T100602Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b2cfe43a-1cab-47bf-bf1c-63c18e9709e1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240613T100602Z
