---
ID: "75f9cd95-5d2e-4bb9-9e6f-e813d52e09d2"
Parent: "f4ded681-693e-43ee-9302-84b70a63edae"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/HeadlessTenant/Hublot/Presentation/Headless Variants/Map/Default
BranchID: "d50624ad-e824-4d9a-b8d1-817b4d0dc929"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{F82C3855-F6EB-4E53-AC22-3320B438D9E5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240530T100747Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7887f7c-445d-41ed-bfaa-f9ef1078b7cb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240530T100747Z
