---
ID: "407db254-1f4d-4eef-b7e3-81b6b2172d70"
Parent: "b1194703-2c98-4818-b4d1-2c5c695bd646"
Template: "b1194703-2c98-4818-b4d1-2c5c695bd646"
Path: "/sitecore/templates/Feature/Components Library/Security-CL/Rendering Parameters/Logout/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4a28bb04-5b41-4182-a08c-c930626f2bf1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240527T144220Z
