---
ID: "9f59db52-b8a3-42d3-93e0-d9655092a47b"
Parent: "87622aab-1d03-4dd3-bc6b-63a3a76c80ef"
Template: "87622aab-1d03-4dd3-bc6b-63a3a76c80ef"
Path: /sitecore/templates/Feature/Hublot/GeneralComponents/Rendering Parameters/SearchResults/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dcdf9814-3984-4373-bebd-35ddf92e4e87"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240401T132234Z
