---
ID: "68c54299-ebd9-4ad2-8bfd-da455ef49b1c"
Parent: "b594af17-b116-4803-878d-20e16a7f3ba4"
Template: "b594af17-b116-4803-878d-20e16a7f3ba4"
Path: /sitecore/templates/Feature/Hublot/GeneralComponents/Rendering Parameters/ProductDetail/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5aa70b2f-9e45-4737-9193-4bde77584dab"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240220T122418Z
