---
ID: "79596de3-848a-451d-b577-7e821f84aba0"
Parent: "b8cc15ae-7ea4-4c8d-92e4-cb32d98f9690"
Template: "b8cc15ae-7ea4-4c8d-92e4-cb32d98f9690"
Path: "/sitecore/templates/Feature/Components Library/Context-CL/Rendering Parameters/SiteSelector/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "079c28a7-5959-4485-aa04-c19b76b1b510"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\darvi.sunny@tadigital.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240513T083553Z
