---
ID: "b5225324-0cc8-4504-8152-603a58ee4d5e"
Parent: "25ec5057-a32c-41e7-bbb2-a9bd3a287ab1"
Template: "25ec5057-a32c-41e7-bbb2-a9bd3a287ab1"
Path: "/sitecore/templates/Feature/Components Library/Media-CL/FileListCL/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{11B9D90E-E86D-48AA-9872-5C2AFA97EA27}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240621T102638Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb027c3c-dd61-4ebd-8838-07c4c4ffc4ea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\amitkumar.verma@credera.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240621T102710Z
